# Generated by Django 2.0.6 on 2018-06-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalScoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='allowed',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('DisAllowed', 'DisAllowed')], default='Allowed', max_length=15),
        ),
    ]
