# Generated by Django 2.0.6 on 2018-06-09 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goalScoreApp', '0002_goals_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goalScoreApp.Teams'),
        ),
    ]
